### ISSUE TITLE
usr/x/bin/bashflix: line 102: pirate-get: command not found

### ISSUE THREAD

**Issue by Rainerr123** [andretavare5/bashflix#25]
get this error when running "bashflix x" have reinstalled twice

"pip3 install pirate-get" shows "Requirement already satisfied" for pirate-get and its requirements.

MacOSX Catalina 10.15.7

**Comment by andretavare5** [comment]
Hi! Thanks for creating the issue. Is pirate-get on your PATH?

**Comment by Rainerr123** [comment]
dont know how to do that but $PATH is set to:
/Users/xxx/bin:/Users/xxx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by andretavare5** [comment]
can you post the error you get when you try to run bashflix please?

**Comment by Rainerr123** [comment]
/Users/xxx/bin/bashflix: line 102: pirate-get: command not found

**Comment by andretavare5** [comment]
Issue fixed with [7284cb6634b4e5e733626ad0cd2792f32f1746b5](https://github.com/andretavare5/bashflix/commit/7284cb6634b4e5e733626ad0cd2792f32f1746b5)
